* Development notes for photo-archive
** Introduction

To get an interactive development environment from the working directory run:

    lein figwheel

and open your browser at [localhost:3449](http://localhost:3449/).
This will auto compile and send all changes to the browser without the
need to reload. After the compilation process is complete, you will
get a Browser Connected REPL. An easy way to try it is:

    (js/alert "Am I connected?")

and you should see an alert in the browser window.

To clean all compiled files:

    lein clean

To create a production build run:

    lein do clean, cljsbuild once min

And open your browser in `resources/public/index.html`. You will not
get live reloading, nor a REPL.

* Development
** Using Co-pilot in GitHub

Get copilot to develop in a branch, and then pull the changes with:

  git fetch origin feature/gallery-and-viewer
  git checkout feature/gallery-and-viewer

where feature/gallery-and-viewer is the feature branch that has been created.

** File System Access API

This application is a local browser based application, which uses an interface
(API) to access the local computer storage directly. 

The API only works in Chromium-based browsers. eg.

- Chrome
- Edge
- Brave
- Vivaldi

It generally does not work in Firefox or Safari.
