* Development of photo-archive

To get an interactive development environment from the working directory run:

    lein figwheel

and open your browser at [localhost:3449](http://localhost:3449/).
This will auto compile and send all changes to the browser without the
need to reload. After the compilation process is complete, you will
get a Browser Connected REPL. An easy way to try it is:

    (js/alert "Am I connected?")

and you should see an alert in the browser window.

To clean all compiled files:

    lein clean

To create a production build run:

    lein do clean, cljsbuild once min

And open your browser in `resources/public/index.html`. You will not
get live reloading, nor a REPL.

** Feature request

- dark mode
-

** Database/Image Archive

images/
  dir1/
    photo1.jpg
    photo2.jpg
  dir2/
    photo2.jpg
  metadata/
    photos.yaml
    albums.yaml
    people.yaml
  
#+begin_src yaml
  photos:
    photo-001:
      path: data/holiday/img1.jpg
      title: Beach
      description: Sunset at the beach
      tags:
        - sunset
        - beach
      people:
        - paul
        - jane

      date: 2025-01-01
      location: Sydney

  albums:
    favourites:
      title: Favourites
      photos:
        - photo-001

  people:
        
#+end_src
